global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "findocai-app"
    static_configs:
      - targets: ["host.docker.internal:8000"]
    metrics_path: "/metrics"
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: "redis"
    static_configs:
      - targets: ["findocai-redis:6379"]  # Using the redis service name from main docker-compose

  - job_name: "node-exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"]